---
# file: roles/nginx/tasks/nginx.yml

- debug: msg="ipv6 address {{ server_name }}"

- name: install nginx package
  sudo: yes
  apt: pkg=nginx state=installed

- name: create nginx ssl directory
  sudo: yes
  file: dest=/etc/nginx/ssl mode=755 owner=root group=root state=directory

- name: copy ssl server crt to box
  sudo: yes
  copy: src=ssl/server.crt dest=/etc/nginx/ssl/server.crt mode=0644

- name: copy ssl server key to box
  sudo: yes
  copy: src=ssl/server.key dest=/etc/nginx/ssl/server.key mode=0644

- name: remove obsolete default nginx config link
  sudo: yes
  file: path='/etc/nginx/sites-enabled/default' state=absent

- name: add konektom site config to sites-available
  sudo: yes
  template: src=site.conf.j2
            dest=/etc/nginx/sites-available/konektom
  notify:
      - restart nginx

- name: add nginx config
  sudo: yes
  template: src=nginx.conf.j2
            dest=/etc/nginx/nginx.conf
  notify:
      - restart nginx

- name: add symlink in nginx sites-enabled
  sudo: yes
  file: src=/etc/nginx/sites-available/konektom
        dest=/etc/nginx/sites-enabled/konektom state=link
  notify:
    - restart nginx

- name: make sure nginx is running
  sudo: yes
  service: name=nginx state=running
